# Numpy Arrays Indexing, Sliciling and Itreation

In [2]:
import numpy as np

In [6]:
arr1 = np.arange(24).reshape(6,4)
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [11]:
arr2 = np.array([1,2,3,4,5])
arr2[3]

4

In [12]:
arr2[2:4]

array([3, 4])

### in numpy arrays the last digit are excluted

In [13]:
arr1[2]

array([ 8,  9, 10, 11])

### if you pass just a single number to 2D array for searching an index it will return the whole row of that number and what if i need the second column of the given 2D arrray what should I do? Think about it.

In [15]:
arr1[:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [16]:
arr1[2:]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [17]:
arr1[:,2]

array([ 2,  6, 10, 14, 18, 22])

In [18]:
arr1[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]])

### Like this we can access a column

In [18]:
arr1[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]])

In [20]:
arr1[2,3]


11

## The Above section was all about indexing

# Slicling Section Start 

## what if you want to access some specific numbers from the given array. So here is the code for example you want to access 9,10,13 and 14 numbers from the array. let's do it

In [22]:
arr1[2:4 , 1:3]

array([[ 9, 10],
       [13, 14]])

### the first 2 numbers represent the number of row(2:4) and the rest of 2 numbers represent the number of column(1:3)

In [23]:
arr1[4:6 , 2:4]

array([[18, 19],
       [22, 23]])

# Itration Section

In [24]:
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [25]:
for i in arr1:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [26]:
for i in np.nditer(arr1):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


## this itration is basically use for when you wanna apply a filter on a specific pexil then we use this itrater function.